name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        run: go build -v -o wave_exploder main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wave_exploder
          path: wave_exploder
